fastmail/Synergy

lib/Synergy/Timer.pm
synergy

Add a saved state file and use it to persist timer and reminders.

saved state!

---

lib/Synergy/User.pm
synergy

Give each user a TZ.  Try to use it when showing them a time.

per-user time zones

---

lib/Synergy/User.pm
synergy

This will resume your last non-aborted non-completed-task timer
that Synergy was tracking.
Synergy will know this from you starting a task with synergy,
or if she discovers an active task in the course of responding
to certain requests.

Add 'resume' / 'resume timer' functionality

---

synergy

Rather than randomly by perl hash ordering!

Projects: sort alphabetically by name

---

lib/Synergy/External/Slack.pm

Then flush them once we've reconnected.
That way, we don't lose any data if we happen to drop our
connection after we've made some changes but before we've
responded to a request.

Queue messages if we're in the process of reconnecting

---

cpanfile
lib/Synergy/LPC.pm

This way things are clickable in the LP UI.

Linkify url-like things in 'commit <....>'

---

lib/Synergy/LPC.pm
lib/Synergy/Reactor/LiquidPlanner.pm

A timer has a total_time and a running_time.
If you stop a timer then later resume it, the total_time is the
total previous time that the timer has accumulated, *not including*
the current running_time of the timer.
So to get the real running time of a timer, we need a new method:
real_total_time()
which combines these two.
I've also added convenience methods to get at friendly readings
of the 3 different times:
running_time_duration
total_time_duration
real_total_time_duration
This gives you something like "1h5m".

Convert LP timers to objects. Use *real total time* when committing work

---

cpanfile
lib/Synergy/Reactor/Roll.pm

```
<robn> synergy roll 2d6
<synergy> rolled 2d6: 3 + 1 = 4
```

Dice-rolling reactor

---

lib/Synergy/Channel/Slack.pm
lib/Synergy/Event.pm
lib/Synergy/External/Slack.pm
lib/Synergy/Hub.pm
lib/Synergy/Reactor/Announce.pm
lib/Synergy/Reactor/Clox.pm
lib/Synergy/Reactor/Eject.pm
lib/Synergy/Reactor/GitLab.pm
lib/Synergy/Reactor/Help.pm
lib/Synergy/Reactor/LiquidPlanner.pm
lib/Synergy/Reactor/Page.pm
lib/Synergy/Reactor/Preferences.pm
lib/Synergy/Reactor/RFC.pm
lib/Synergy/Reactor/Reminder.pm
lib/Synergy/Reactor/Roll.pm
lib/Synergy/Reactor/Rototron.pm
lib/Synergy/Reactor/SlackID.pm
lib/Synergy/Reactor/Status.pm
lib/Synergy/Reactor/Upgrade.pm
lib/Synergy/Reactor/Who.pm
lib/Synergy/Role/Channel.pm
lib/Synergy/Role/HasPreferences.pm
t/exclusive.t

This might actually be ok, though it needs a bit of polish. I have done basically no testing with non-slack channels yet. The first commit here is almost entirely whitespace.

Respond to slack edits

---

lib/Synergy/Reactor/Preferences.pm

Seriously I spent ten minutes this morning trying to figure out what one of the prefs was named and what mine was set to.

prefs: more ways to ask for settings

---

lib/Synergy/Channel/Test.pm
t/agenda.t
t/lib/Synergy/Tester.pm

easier testing via testergize

---

lib/Synergy/Reactor/InABox.pm
t/inabox.t

Reduce copy/paste, convert to fully async, add a test.

Inabox reactor refactor

---

lib/Synergy/Reactor/VictorOps.pm
t/victorops.t

`ack-all` was taken from Michael's fork.
This allows a user to ack all current incidents.
`resolve all` resolves all current acked incidents.
`resolve mine` resolves all current acked incidents that the user acked.
My gripes:  
I don't like how i've handled the difference between mine vs all in the subroutine signature.  It's rather opaque for someone looking at a handler and seeing a 0 or 1 passed in to `_resolve_acked()`

Victorops: ack-all, resolve-all, resolve-mine

---

lib/Synergy/Channel/Pushover.pm
lib/Synergy/Channel/Twilio.pm
lib/Synergy/Hub.pm
lib/Synergy/Reactor/CatPic.pm
lib/Synergy/Reactor/GitLab.pm
lib/Synergy/Reactor/HelpSpot.pm
lib/Synergy/Reactor/HighFive.pm
lib/Synergy/Reactor/InABox.pm
lib/Synergy/Reactor/LiquidPlanner.pm
lib/Synergy/Reactor/VictorOps.pm
lib/Synergy/Reactor/Weather.pm

or, well, they return futures, anyway

Hub: all http requests are now async

---

cpanfile

Dependency added in December last year, commit e3a7755f2b14273c1877eb16986902b994a9d1cb

cpanfile add crypt mac hmac

---

lib/Synergy/Reactor/LiquidPlanner.pm

LiquidPlanner: you can meet goals to get a :tada:

---

cpanfile

Required by the inabox reactor

cpanfile: add Safe::ISA

---

.gitignore
lib/Synergy/Reactor/Zendesk.pm

I don't want to merge this until I've removed it from Bort.

Zendesk: handle imported tickets

---

lib/Synergy/Reactor/InABox.pm

Please feel free to merge and deploy at leisure.

InABox: use a bigger droplet size by default

---

lib/Synergy/Reactor/PagerDuty.pm

With VictorOps the slack integration announced when there is an oncall
change.
Pager Duty does it silently.  Synergy can pick up the slack (pun intended).
Anyway, not sure how many people found the announcement useful.  I know I did, and speaking to Butch he does too.

pd: announce @oncall changes

---

lib/Synergy/Reactor/Linear.pm

This does *not* honor the default team of the user, so that asking
for a user's agenda finds their items across all teams.

Linear: Add 'Lagenda' cmd, takes no args, user, team, or user@team

---

lib/Synergy/Reactor/LinearNotification.pm

That is, any task created with the configured label will send
a message to the configured slack channel about it

Add Synergy::Reactor::LinearNotification - handles triage tasks

---

lib/Synergy/Reactor/TimeClock.pm

Sometimes, we get into some state where a newly added or deleted user
causes the time-clock reactor to crash midway through reports. This
means that all the users _before_ the crash often get a skrillion
morning/evening reports, because we boot up, start sending reports,
then crash before setting our "last report" time, over and over again.
That stinks for the users who get a million reports, so instead we'll
store last report time by user. This is slower, because we save our
state to the sqlite database after every user, but they're reports and
it doesn't matter if they're slow!

TimeClock: record last report time per-user

---

lib/Synergy/Rototron.pm

Rototron: Don't try to jsonify DateTime objects, it will die!

---

.gitignore
bin/synergy
cpanfile
lib/Synergy/Channel/Console.pm
lib/Synergy/CommandPost.pm
lib/Synergy/DiagnosticHandler.pm
lib/Synergy/DiagnosticUplink.pm
lib/Synergy/Event.pm
lib/Synergy/External/Slack.pm
lib/Synergy/HTTPServer.pm
lib/Synergy/Hub.pm
lib/Synergy/Logger.pm
lib/Synergy/Logger/Test.pm
lib/Synergy/PotentialReaction.pm
lib/Synergy/Reactor/GitLab.pm
lib/Synergy/Reactor/Linear.pm
lib/Synergy/Reactor/PagerDuty.pm
lib/Synergy/Reactor/Register.pm
lib/Synergy/Rototron.pm
lib/Synergy/Timer.pm
lib/Synergy/UserDirectory.pm
lib/Synergy/Util.pm
t/basic.t
t/httpendpoint.t
t/lib/Synergy/Test/CommandPost.pm

I want to rebase bortergy onto synergy to get a year's worth of minor improvements, and realized that there were some things that would be good to backport into synergy prime.

Bort backports

---

lib/Synergy/Reactor/Vestaboard.pm

I've wanted this twice this week!

Vesta: allow admins to grant board tokens

---

lib/Synergy/Reactor/Linear.pm

@mmcclimon this is just a small annoyance fix

Linear: add extra space btw issue desc and slack link

---

lib/Synergy/Reactor/Linear.pm

This eliminates unnecessary api calls and makes everything a little speedier

Replace 'get_authenticated_user' with isMe filter

---

lib/Synergy/Reactor/Linear.pm

Synergy will react to "comment on plu-xxx: comment" by adding a comment to the given issue

Linear Reactor: comment on Linear issues

---

lib/Synergy/Reactor/InABox.pm

Dumb little change.  I don't touch Synergy very often these days and was fiddling with it anyway so I thought why not 🤷

inabox: Make box size as a config option

---

lib/Synergy/Reactor/Zendesk.pm

@wolfsage I am not sure how to test this locally.

Zendesk reactor: skip getting zendesk tickets if user has no zendesk account

---

lib/Synergy/Reactor/InABox.pm

You can now say "box create /setup" and have it do things to make you comfortable when it starts working.

InABox: the /setup switch

---

lib/Synergy/Reactor/PagerDuty.pm

I stepped into several traps and broke the build. This fixes it.

Fix syntax error

---

lib/Synergy/Reactor/GitLab.pm
lib/Synergy/Reactor/InABox.pm

I really dislike getting a raw text file reply when something goes wrong!

Inabox setup snippet

---

lib/Dobby/Client.pm
lib/Synergy/Reactor/InABox.pm

This adds a Dobby method to get every page of results, concatenating the Array found in a given key from each page.  Then it uses it for SSH keys.

InABox: cope with paginated data for ssh_keys

---

t/inabox.t

The comment added in this commit describes things, so I will reproduce it here:
This is sort of idiotic, by which I mean a few things:
* This code is doing something stupid because that's how to make it work.
* I am (only a little bit) an idiot for making this necessary.
* This is stupidly unoptimized because optimizing something like this is stupid.
The above *should* work, but it only measures that every event has been sent through the queue.  Instead, we should make exhaustion on the test channel mean that every fired reaction handler has fully completed. This is probably doable, but it will need some real thinking.  Instead, we are going to just let the loop run for one quarter second.
Annoyingly, this code was not needed on Rik's laptop, either because it's very fast or because the …

InABox: add a sleep-like loop to tests

---

lib/Synergy/Reactor/InABox.pm
t/inabox.t

Just a convenience thing I should have created when added better replies when the region isn't available in fb7f3ca.
Also fixed the wording, which was apparently always wrong.

InABox: add /datacentre switch

---

README.mkdn
eg/local.json
eg/users.yaml

Update the README to remove pitfalls, and update the sample config in eg:
* Remove the linear reactor since without an API key synergy will crash when loading
* Add eg/users.yaml (copied from test data) as without one, synergy will crash when loading

Update sample config and readme for local development

---

lib/Synergy/Reactor/GitLab.pm

Shows a list of recently run pipelines and their success status, with a link to the results.
The idea is to easily see when run-perl-tests has stopped / started failing.

Gitlab: add pipelines command

---

lib/Synergy/Reactor/InABox.pm

`box image` will print information on what image a box would be created with when invoking box create.  Mostly concerned with the age of the snapshot

InABox: add 'box image' command

---

lib/Synergy/Reactor/GitHub.pm

I read about this great new feature and felt very left out of the club when i tried to join it.

GitHub: allow dashes in usernames

---

lib/Synergy/Reactor/PagerDuty.pm

New features for `give oncall` command:
1. Be smarter about picking who to overrride
2. Automatically determine how long to override if possible

overhaul "give oncall" command

---

lib/Synergy/Reactor/PagerDuty.pm

The 'incident' command now shows notes attached to live incidents.
This allows responders to leave notes for others who may need to check / respond to long-running incidents, and encourages them to do so.

Show incident notes
