lib/Synergy/User.pm
synergy

For some reason, some of the requests we make to liquid planner cause
POE::Component::Client::HTTP to never return (right now, 'tasks' is doing
this consistently!)
Use Net::Async::HTTP instead which seems to handle requests just fine.

Replace LWP::UserAgent::POE with Net::Async::HTTP

---

synergy

Supports any of the lp task urls, as long as the final number
identifies a task

Allow "spent time on <lp task url>" to log time against a task

---

lib/Synergy/HTTPServer.pm
t/https.t

Otherwise every clown with a broken SSL negotation (eg plain HTTP requests) crashes Synergy.

HTTPServer: log SSL errors, but don't die

---

lib/Synergy/Reactor/Weather.pm

Uses the [OpenWeatherMap API](https://openweathermap.org/current) to get the current weather.
Typical config:
```json
"weather": {
"class": "Synergy::Reactor::Weather",
"api_token": "...",
"locations": [
"Melbourne,AU",
"Philadelphia,PA,US"
]
}
```
There's various bugs/nits/shortcomings:
- day/night icons indicate [day/night at UTC](https://openweathermap.desk.com/customer/portal/questions/16800670-forecast-returns-night-times-)
- there's not a full icon set for night
- there's more data we could show
- maybe the formatting sucks
- maybe it could use the caller's units
- maybe [forecasts](https://openweathermap.org/forecast5) would be good
Is this even useful? I didn't really have an idea of what I wanted; I just wanted to fiddle with something.

Initial weather report reactor

---

lib/Synergy/Channel/Pushover.pm
lib/Synergy/Channel/Slack.pm
lib/Synergy/Channel/Test.pm
lib/Synergy/External/Slack.pm
lib/Synergy/Hub.pm
lib/Synergy/Reactor/Page.pm
lib/Synergy/Reactor/Register.pm
lib/Synergy/User.pm
lib/Synergy/UserDirectory.pm

This converts the user directory into a set of tables in the sqlite database. It'll auto-upgrade from an existing user-directory file on the fly.
The only thing in the user table that probably shouldn't be is `lp_id`, but removing that was gonna be a pain because we also have virtual users who can't self-register. That's a problem for another day.

Self-registration!

---

lib/Synergy/Reactor/LiquidPlanner.pm
t/lp-task-spec.t

Given:
foo ^bar name:Bob name:Alice name:Bob baz page:2 created:before:2019-01-01
Before, we built:
{
words => [
{ word => 'foo', op => 'contains' },
{ word => 'bar', op => 'starts_with' },
{ word => 'baz', op => 'contains' },
],
kvs   => {
name => { Alice => 1, Bob => 1 },
page => { 2 => 1 },
'created:before' => { '2019-01-01' => 1 },
}
}
Now, we build:
[
{ field => 'name',    op => 'contains',     value => 'foo'        },
{ field => 'name',    op => 'starts_with',  value => 'bar'        },
{ field => 'name',                          value => 'Bob'        },
{ field => 'name',                          value => 'Alice'      },
{ field => 'name',                          value => 'Bob'        },
{ field => 'name',    op => 'contains',     value => 'baz'        },
{ field => 'page', …

LiquidPlanner: rewrite the search parser

---

lib/Synergy/External/Slack.pm

Not the USER address like chat.postMessage uses

For slack, $event->private_reply text only needs DM address

---

lib/Synergy/Reactor/InABox.pm

This adds new preferences to the inabox reactor.  It also adds the workaround for the reactor crashing when a snapshot isn't found as detailed in #123 
A user can only set a preference based on jessie and buster, but any string can be put in for `/version <foo>` so that if something experimental is being worked on it can be namespaced without needing any configuration change.  Eg `box create /version my-experiment`
The data centre preference will default to the existing behaviour of picking a DC based on timezone, unless a preference has been set.  
At the moment there is no checking of the data centre.  Michael suggested config for this, but i don't think that's the right fit.  For example I recently added Singapore to DC's we upload the nightly snapshot to, but I have no idea what DC's …

Inabox new prefs datacentre and version

---

lib/Synergy/Reactor/InABox.pm

Extending `/version` and adding `/tag`, to be able to create multiple boxes, each with different names and/or versions.
After deploying, I will rename all existing boxes to be <username>-jessie, which should make the change pretty much invisible to people that only want/need one box.
I think it could be made a lot nicer, particularly when it comes to targetting existing boxes. On the other hand, this should mostly be unuseful except outside of the OS upgrade in progress and certain weird situations, and a little friction maybe isn't bad because we don't actually want people creating multiples most of the time.

inabox: add support for multiple boxes

---

lib/Synergy/Reactor/VictorOps.pm

Sometimes operators forget to demaint.
Create a timer that fires every 30 minutes to @oncall in plumbing and remind them we're in maint.
Not sure if how i've set up the timer etc is the best way to do things.  Especially removing the timer.

vo: maint timer periodically notifies oncall we're still in maint

---

lib/Synergy/Reactor/Status.pm

The use of `shift` was a mistake, it should have been `$shift`

Status Reactor: Report when someone in another time zone is off

---

lib/Synergy/Reactor/PagerDuty.pm

NOTE: this is almost certainly incompatible with the VO reactor. It's possible they might both work at the same time, but I haven't tested it.
This is more or less a direct port of the VictorOps reactor, with the necessary changes for the differences between the two services. It's likely we'll want to improve this somewhat, but this gets us to feature parity. The commit messages have more detail, where necessary.
The most notable thing I _didn't_ port was extra behavior on demaint: that is `demaint /resolve` is no longer a thing, nor is `demaint /noresolve`, which never quite worked right anyway.

PagerDuty reactor

---

lib/Synergy/Reactor/InABox.pm

There are some droplet types available in sfo3 that Butch wants for the
automated testing work.  It doesn't make sense to have snapshots at both
sfo2 and sfo3 long term so update the default so we can remove the snapshots from sfo2.
There will be some users with a preference set for sfo2.  Would it be best to "send an email" to get everyone with it manually set to update it, or just update it from underneath them (and if so, how?)

inabox: move default datacentre for AU sfo2 --> sfo3

---

lib/Synergy/Environment.pm
lib/Synergy/Hub.pm
lib/Synergy/Reactor/Prometheus.pm
lib/Synergy/Role/HubComponent.pm
t/prometheus.t

I want to be able to use this from more places, and making it
first-class seems reasonable.

Move prom object out of reactor and into hub

---

lib/Synergy/Reactor/Fortune.pm
lib/Synergy/Reactor/GitLab.pm
lib/Synergy/Reactor/Zendesk.pm

My take: no reason to leave things sitting on the event loop all the time.  Instead, we'll let things wait to get cleaned until the next read.  In theory, some more memory might get left committed, but it's tiny hash entries in all cases.

replace timers to clear caches with just-in-time reaping

---

lib/Synergy/Reactor/GitLab.pm
lib/Synergy/Reactor/Zendesk.pm
lib/Synergy/Role/DeduplicatesExpandos.pm

This removes the copypasta from the GitLab and Zendesk reactors, and
lets us reuse that in the future for other informational expando things.

Add DeduplicatesExpandos role, use it

---

lib/Synergy/CommandPost.pm
lib/Synergy/Reactor/CatPic.pm
lib/Synergy/Reactor/Clox.pm
lib/Synergy/Reactor/Help.pm
lib/Synergy/Role/Reactor.pm
lib/Synergy/Role/Reactor/EasyListening.pm

CommandPost: a new framework for coding reactions
In previous versions of Synergy, all reaction was governed by Listener objects, which set the form for how reaction could occur.  This was replaced by the "potential_reactions_to" method, which more readily allowed reactors to choose their own means by which to react to events.
CommandPost is proof of concept of a new way to build reactors.  It puts more things in one place.  It simplifies the common cases of writing named commands and mention-listeners.  It helps avoid duplication, for example repeating a regex in the reaction body as well as the EasyListening-style predicate sub.
Instead of predicates, CommandPost provides "matchers", which return a value that can then be fed to the reaction method, allowing for single-pass parsing (for …

CommandPost: a new framework for coding reactions

---

lib/Synergy/Reactor/LinearNotification.pm

A couple of small fixes:
- The notification message specifies if the escalated issue was
created from Zendesk or updated to escalation in Linear
- The notification message was incorrectly identifying the person who
moved a issue to escalation as the creator of the issue, rather than
the person who added the support blocker label. Linear does not give
us an easy way to determine who the actor was, so we're removing this
bit of info for now.

LinearNotification: updates to slack notification message

---

lib/Synergy/CommandPost.pm
lib/Synergy/Reactor/CatPic.pm
lib/Synergy/Reactor/Clox.pm
lib/Synergy/Reactor/GoodMorning.pm
lib/Synergy/Reactor/Linear.pm
lib/Synergy/Reactor/Zendesk.pm
lib/Synergy/Role/DeduplicatesExpandos.pm
lib/Synergy/Role/Reactor.pm
lib/Synergy/Role/Reactor/CommandPost.pm
t/commandpost.t
t/lib/Synergy/Test/CommandPost.pm

1. I refactored CommandPost to make it a little (only a little) simpler
2. I wrote a testing library for testing CommandPost itself
3. I converted the Linear reactor to CommandPost
4. I added command aliases to CommandPost
5. I added "parsers" to commands; these probably need more work in the future

CommandPost: refactored, testable, extended

---

lib/Synergy/Reactor/PagerDuty.pm

To often i find myself forgetting that the command is incidents and type
alerts.  Now i won't have that problem

pager duty: add an alias 'alerts' map to 'incidents'

---

lib/Synergy/Reactor/Linear.pm

When creating a linear issue from slack, add the slack link to the issue
so we can see any background discussion around the task creation

Linear: add slack link to linear issue

---

lib/Synergy/Reactor/InABox.pm
t/inabox.t

This updates the `inabox.version` and `inabox.datacentre` preferences.  They're now derived from config, with only a default 'buster' hard coded if the property isn't set.

Inabox preference updates

---

lib/Synergy/Channel/Pushover.pm
lib/Synergy/Channel/Twilio.pm

Otherwise if you `synergy upgrade` from Twilio, when it restarts it'll keep crashing trying to send the "I updated!" message.
Oops!

Pusher/Twilio: send_message final argument should be optional

---

lib/Synergy/Reactor/InABox.pm

DigitalOcean now have a datacentre in Sydney and the images are being copied there.

InABox: Update datacentre default in Australia

---

Makefile.PL
lib/Synergy/Channel/Test.pm
lib/Synergy/Hub.pm

This makes it so that Synergy::Channel::Test's is_exhausted can take into account whether or not a reactor is waiting on an external HTTP service before responding.
Without this, `$channel->is_exhausted` would return true, even if a reactor hadn't had a chance to respond yet.

Synergy::Hub: Track in-flight http requests

---

lib/Synergy/Hub.pm
lib/Synergy/Reactor/Clox.pm
lib/Synergy/Reactor/DiagnosticEvents.pm
lib/Synergy/Reactor/GitLab.pm
lib/Synergy/Reactor/InABox.pm
lib/Synergy/Reactor/Linear.pm
lib/Synergy/Reactor/Page.pm
lib/Synergy/Reactor/PagerDuty.pm
lib/Synergy/Reactor/Preferences.pm
lib/Synergy/Reactor/RememberTheMilk.pm
lib/Synergy/Reactor/TimeClock.pm
lib/Synergy/Reactor/Todo.pm
lib/Synergy/Reactor/Zendesk.pm
lib/Synergy/Role/HasPreferences.pm
lib/Synergy/UserDirectory.pm

The big goal here was "allow a preference describer to be async, so it can look up an opaque identifier in a remote API without locking up the whole bot".  To accomplish that, or as closely related work…
* the HasPreferences system uses async/await and made validator, describer, and after_set async
* the describer callback gets the reactor as first arg
* all reactors using those callbacks were updated to use the new semantics
* the Preferences reactor was updated to match, and to use CommandPost and async/await
* the PagerDuty reactor was updated to use CommandPost and async/await (see below)
* the Linear reactor was updated to use the Linear API to describe the default team setting
The PagerDuty reactor was pretty extensively updated.  It didn't need to be, strictly, but while doing this …

convert preference properties to async/await (and associated work)

---

lib/Synergy/Reactor/Page.pm
t/page.t

The Page rector will then check with the PagerDuty reactor for who is oncall, then page the appropriate people

page reactor: add support to page oncall

---

lib/Synergy/Hub.pm
lib/Synergy/Reactor/PagerDuty.pm

Changes the pagerduty reactor service_id config to service_ids so we can have synergy looking after multiple services.

Pagerduty multi service

---

lib/Synergy/Reactor/InABox.pm

The 'fminabox' key is defunct.  I've added synergy's key as 'synergy' so it's clear where that key is.  And this makes it configurable so if we ever have a future fminabox where we don't purge cloud-init then it can be configurable

InABox: make the DO ssh key name configurable

---

lib/Synergy/Reactor/InABox.pm
t/inabox.t

When a snapshot is unavailable in the users datacentre it's much nicer to reply with a better response than "Something weird happened..."

InABox: Check snapshot regions before creating box

---

lib/Synergy/Reactor/InABox.pm

It's common for me to use a phone to ask Synergy to spin up an Inabox, so by the time i'm at my desk it's ready to go.
My phone also likes to capitalise words.
I'm a bit tired of stubbing my proverbial toe after 'box create /version Bookworm' and being told there is no 'Bookworm' version available because of case sensitivity.

InABox: version and tags only lowercase

---

lib/Synergy/Reactor/Page.pm
t/page.t

Synergy pages can use an ephemeral channel such as a voice call.
This change allows to configure a secondary channel that is intended to be a permanent reference copy for the recipient.

Page: Create a carbon copy of a page

---

lib/Synergy/Reactor/Transliterate.pm
lib/Synergy/UserDirectory.pm
t/transliterate.t

1.  fix the default user.alphabet to Latin ("English" was harmless but wrong)
2.  on bogus use of "transliterate" provide the right usage, rather than claiming that it is an unknown alphabet
3.  tests!!

Transliterate: improve error message, add a test

---

lib/Synergy/Reactor/TimeClock.pm

The old code has this:
my $report = $report_reactor->begin_report($report{$which}, $user);
my ($text, $alts) = $report->get;
next unless defined $text; # !? -- rjbs, 2019-10-29
$Logger->log([ "sending %s report for %s", $which, $user->username ]);
$channel->send_message_to_user($user, $text, $alts);
That ->get means the whole `check_for_shift_changes` method, called by an every-15m timer, would block.  Worse, it would convert any failed future into an exception, and because `check_for_shift_changes` isn't called from a reaction, it isn't handled by the hub's usual exception handler.
This fix is fairly crude, but it should avoid blocking and crashing. Future work should...
* convert this stuff to async/await!
* add an uptime gauge to the Prometheus endpoint
* improve how we log errors …

TimeClock: avoid blocking and dying (those are bad)

---

lib/Synergy/Reactor/PagerDuty.pm

We are putting all the incident text into one slack post text block, which is too much text for one block when there's too many incidents.
Split it up into one block per incident instead.
This is untested because every time I want to test a synergy change I have to figure out how to run Synergy again from scratch.

PagerDuty: Split incident text blocks

---

lib/Synergy/Environment.pm
lib/Synergy/HTTPServer.pm
lib/Synergy/Hub.pm

Wasn't sure what ip address Synergy was listening on, then realised she was listening on everything.  Keep that default but allow specifying specific IPs

HTTPServer: specify IP address

---

lib/Synergy/Reactor/GitLab.pm

This has been broken since 98df89e when it was changed to use `hub->http_post`
Other than `Content` and `Content_Type` k:v pairs, `hub->http_request()` presumes all other k:v pairs are headers.
By calling with with headers => { foo=> bar }, the actual arguments into http_client->do_request() were
headers => { headers => { foo => bar } }
instead of
headers => { foo => bar }

GitLab: Fix post_gitlab_snippet headers

---

lib/Synergy/Reactor/InABox.pm

Currently when generating vpn config we are always including the tag in the fqdn generated. eg 'user-bullsye.boxdomain.com'
This is fine until we bump the default version from bullseye -> bookworm and people get understandably confused when their vpn doens't work any more.
On 'box create' without a /version or /tag passed in we setup dns for both the 'user-tag.boxdomain.com' and 'user.boxdomain.com' (the latter was the only thing we had before we added multiple box support).
So lets rely on the dns entry omitting the tag by default when invoking 'box vpn' without a /version or /tag switch

InABox: box vpn omit tag in hostname by default

---

lib/Synergy/Channel/Slack.pm
lib/Synergy/External/Slack.pm
lib/Synergy/Reactor/InABox.pm
lib/Synergy/Reactor/SlackID.pm

files.upload is deprecated, use new method of files.getUploadURLExternal then files.completeUploadExternal

Slack: rewrite send_file using new Slack APIs

---

lib/Synergy/Reactor/Preferences.pm

Backticks are great in Slack and presumably Discord.  Look very out of place in the console.
Before:
```
│ Preferences for adavis: ```clox.include-aelt: 0
│ gitlab.user-id: <undef>
```
After
```
│ Preferences for adavis:
│ clox.include-aelt: 0
│ gitlab.user-id: <undef>
```

Preferences: No backticks in console

---

lib/Synergy/Reactor/InABox.pm
t/inabox.t

This way, you don't accidentally destroy the wrong box if you do
synergy: box destroy /label foo /force
... when you meant ...
synergy: box destroy /tag foo /force
The former would estroy your base box image, the latter would destroy the specifically tagged image.

Inabox: destroy: Strictly validate arguments

---

share/splitflap/editor.js

A recent Firefox update seems to have done _something_ to have broken
native input selecting option values by their text when typing at a
normal speed.  I didn't try very hard to track down what the change
in Firefox actually was, because it's almost lunch time on a Saturday.
Instead, let's just force the issue and not try to use native input
anymore.

Splitflap editor: fix input on Firefox

---

lib/Synergy/DiagnosticHandler.pm

This is just to avoid typing and thus typos.

DiagnosticHandler: add some shortcuts to /eval

---

lib/Synergy/Reactor/Linear.pm

The 'triage' command by default shows only unassigned issues, in order to assist with triaging tickets created or moved from other teams.
However, tickets we (in PLAT) create for triage through `synergy ++` will have the creator assigned. This is fine but we want to be able to query synergy for these tickets, so we do that with `synergy triage plat /all`.
Ticket: PLAT-2422

Reactor/Linear: Implement 'triage /all'

---

lib/Synergy/Reactor/Page.pm
lib/Synergy/Reactor/PagerDuty.pm

"page oncall /all" will page everyone in the final oncall escalation, as a last resort emergency flare.
This requires redoing the argument parsing in the page command, and implementing a function in the PagerDuty module to determine all the users in the oncall escalation.

Reactor/Page: Implement "page oncall /all"

---

lib/Synergy/Reactor/InABox.pm

Had a minor bug where the wrong snapshot was spun up because it matched `fminabox-$version` but had additional stuff afterwards that sorted earlier
This isn't a fix the issue it's possible to create non main builds that collide in snapshot name, but at least they'll time out being the snapshot synergy grabs in <24 hours

InABox: sort snapshots exclusively by created_at time

---

lib/Synergy/Reactor/InABox.pm

Because of inabox changes, `fmdev mysetup` now needs to be run on every deployed inabox.
So we make the ssh_key_id private key file mandatory and rejigger the setup logic so that it always runs and passes the new "--no-custom" argument to fmdev mysetup if the custom setup shouldn't run.

Reactor/InABox: Setup is now mandatory

---

lib/Synergy/Reactor/InABox.pm

I always type "/region" on the first try because I've spent too much time in the cloud so region is the natural concept in my head rather than datacentre. So let's make the robot accomodate the human.

InABox: Add support for /region alias for /datacentre

---

ci/before-build

We recently had some breakage on Synergy's inabox tests because the CI didn't run them, because it was set to skip the Dobby tests if Dobby wasn't installed.  This is foolish.  CI should actually test it all.
Because Dobby is not on the CPAN, we need a way to install it some other way.  To accomplish this, I've extended the dzil-actions definition of tarball testing to allow them to run a `./ci/before-build` program before the dist is built.
This PR adds such a program for Synergy, adding Dobby.

ci/before-build: run things before build in CI

---

lib/Synergy/BoxManager.pm
lib/Synergy/Reactor/InABox.pm
t/01-compile.t
t/inabox.t

Synergy is great and all, but sometimes it's nice to manage boxes from outside of chatops.  Making that possible was the real reason behind ever writing Dobby, and this commit realizes it.  This abstracts box management (create, destroy, setup, power events) from the InABox reactor.
The BoxManager needs to be given callbacks for chatops things like sending replies.  In a console environment, these can be replaced with something like "print".

Synergy::BoxManager: inabox management outside the hub

---

lib/Synergy/BoxManager.pm
t/inabox.t

Previously, when setting up a box called user-ident:
* create A record for user-ident.box.${boxdomain}
* if it's the default box: create A record for user.box.${boxdomain}
Now:
* create A record for user-ident.box.${boxdomain}
* if it's the default box: create CNAME record for user.box.${boxdomain}
This may change yet further, but it establishes that the "default" record is of a different type.

BoxManager: change how DNS records are set up

---

lib/Synergy/Reactor/InABox.pm

With the box domain changed, we "need" a way to destroy old boxes that have a different domain.  This addresses that problem.

InABox: box obliterate, a temporary command

---

lib/Synergy/Reactor/PagerDuty.pm

The help message needed to be updated for the recent oncall changes. This change is docs only.

Reactor/PagerDuty: Update help
